### ISSUE TITLE
Change Direction RTL 

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#20]
Add right-to-left direction when switching to Arabic.

``` css
.sidebar {
  direction: rtl;
}
```

Also make sure, the icons alignment looks correct (add margin):

![image](https://cloud.githubusercontent.com/assets/1521/10249700/fae867b6-6926-11e5-8a9a-1fc4650535f8.png)
